// implementing/ng-test-simple-mask-money/src/app/app.component.ts
import { SimpleMaskMoney } from 'simple-mask-money'; // import mask
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
  <!-- 
    inner html you put type text and inputmode numeric to mobile show numeric keyboard 
  -->
  <input [(ngModel)]="val" (input)="val=SimpleMaskMoney.format(val)" (keyup)="send()"/>
  `
})
export class AppComponent implements OnInit {

  // declare mask in your class to use in html templete
  SimpleMaskMoney = SimpleMaskMoney; // if you prefer use only in class this line is not necessary

  // Your value
  val = '0,00';

  constructor() { }

  ngOnInit() {
    // configuration       
    SimpleMaskMoney.args = {
      preffix: '',
      suffix: '',
      fixed: true,
      fractionDigits: 2,
      decimalSeparator: ',',
      thousandsSeparator: '.'
    };
  }

  // Your send method 
  send() {

    // This method return value of your input in format number to save in your database
    SimpleMaskMoney.formatToNumber(this.val);
  }
}

// implementing/v-test-simple-mask-money/src/App.vue
<template>
  <div>
    <!-- inner html you put type text and inputmode numeric to mobile show only numbers -->
    <input type="text" inputmode="numeric" v-model="val" v-on:input="val = SimpleMaskMoney.format(val)" v-on:keyup="send()">
  </div>
</template>

<script>
import { SimpleMaskMoney } from '../../../lib/simple-mask-money'; // import mask

export default {
  data() {
    // declare mask in your local
    return {
      SimpleMaskMoney: SimpleMaskMoney,
      val: '0,00'
    }
  },
  created() {
    // configuration   
    SimpleMaskMoney.args = {
      preffix: '',
      suffix: '',
      fixed: true,
      fractionDigits: 2,
      decimalSeparator: ',',
      thousandsSeparator: '.'
    };
  },
  methods: {
    // Your send method 
    send() {

      // This method return value of your input in format number to save in your database
      SimpleMaskMoney.formatToNumber(this.val);
    }
  }
}
</script>
